console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  blue = '#209be3'
  dark-blue = '#161e38'
  orange = '#e35b12'
  white = '#e9edf5'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ .Icon }} '
    foreground = 'p:white'
    background = 'p:dark-blue'
    type = 'os'
    style = 'diamond'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ .UserName }}@{{ .HostName }} '
    foreground = 'p:white'
    background = 'p:orange'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = '<transparent,p:blue></>'
    trailing_diamond = ''
    template = ' {{ .Path }} '
    foreground = 'p:white'
    background = 'p:blue'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      folder_icon = '...'
      folder_separator_icon = '<transparent>  </>'
      home_icon = ''
      style = 'agnoster_short'

  [[blocks.segments]]
    leading_diamond = '<transparent></>'
    trailing_diamond = ''
    template = '  '
    foreground = 'p:white'
    background = 'p:dark-blue'
    type = 'status'
    style = 'diamond'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date .Format }}  '
    foreground = 'p:dark-blue'
    background = 'p:white'
    type = 'time'
    style = 'diamond'

    [blocks.segments.properties]
      time_format = '15:04:05'
