"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2

[palette]
white = "#e9edf5"
orange = "#e35b12"
dark-blue = "#161e38"
blue = "#209be3"

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "os"
style = "diamond"
background = "p:dark-blue"
foreground = "p:white"
leading_diamond = "\ue0b6"
template = " {{ .Icon }} "

[[blocks.segments]]
type = "session"
style = "diamond"
trailing_diamond = "\ue0b0"
background = "p:orange"
foreground = "p:white"
template = " \uf26c {{ .UserName }}@{{ .HostName }} "

[[blocks.segments]]
type = "path"
style = "diamond"
trailing_diamond = "\ue0b0"
leading_diamond = "<transparent,p:blue>\ue0b0</>"
template = " {{ .Path }} "
background = "p:blue"
foreground = "p:white"

[blocks.segments.properties]
folder_separator_icon = "<transparent> \ue0b1 </>"
home_icon = "\ueb06"
style = "agnoster_short"
folder_icon = "..."

[[blocks.segments]]
type = "status"
style = "diamond"
leading_diamond = "<transparent>\ue0b0</>"
trailing_diamond = "\ue0b4"
background = "p:dark-blue"
foreground = "p:white"
template = " \ue23a "

[blocks.segments.properties]
always_enabled = true

[[blocks]]
type = "rprompt"
alignment = "right"

[[blocks.segments]]
type = "time"
style = "diamond"
background = "p:white"
foreground = "p:dark-blue"
leading_diamond = "\ue0b6"
trailing_diamond = "\ue0b4"
template = " {{ .CurrentDate | date .Format }} \uf017 "

[blocks.segments.properties]
time_format = "15:04:05"
