[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

[default_session]
command = "tuigreet --cmd sway --time --remember --remember-user-session --asterisks --greeting WELCOME --theme 'border=darkgrey;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=black;input=red'"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
